# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ie0WzFutMPyVpw6xPiQvv6hejiCx54B9
"""

import urllib.request
import zipfile
import os

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip"
zip_file_name = "smsspamcollection.zip"
urllib.request.urlretrieve(url, zip_file_name)

# Extract the zip file
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall(".")

# Remove the zip file after extraction
os.remove(zip_file_name)

import pandas as pd

# Load the data
df = pd.read_csv('SMSSpamCollection', sep='\t', header=None, names=['label', 'message'])

# Map labels to binary
df['label_num'] = df.label.map({'ham':0, 'spam':1})

print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label_num'], test_size=0.3, random_state=42)

# Convert text to a matrix of token counts
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Train the classifier
nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

# Predict on test set
y_pred = nb.predict(X_test_vec)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))