# -*- coding: utf-8 -*-
"""k-means-cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ge6F1RpOPNqSQc2pxuAZe_CVEmcUwqmk
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

data_url = "https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/master/Datasets/Mall_Customers.csv"
df = pd.read_csv(data_url)

print("First 5 rows:")
print(df.head())

X = df[["Age", "Annual Income (k$)", "Spending Score (1-100)"]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

wcss = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, init="k-means++", random_state=42, n_init="auto")
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(6, 4))
plt.plot(range(1, 11), wcss, marker="o")
plt.title("Elbow Method for Optimal k")
plt.xlabel("Number of clusters (k)")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

k_optimal = 5
kmeans = KMeans(n_clusters=k_optimal, init="k-means++", random_state=42, n_init="auto")
clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters
print("\nData with cluster labels:")
print(df.head())

plt.figure(figsize=(6, 4))
for c in range(k_optimal):
    cluster_points = df[df["Cluster"] == c]
    plt.scatter(
        cluster_points["Annual Income (k$)"],
        cluster_points["Spending Score (1-100)"],
        label=f"Cluster {c}"
    )

plt.title("Customer Segments (K-Means)")
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1–100)")
plt.legend()
plt.grid(True)
plt.show()

